static const uint genomeSize = 8; /** The number of genes in the genome */
static const uint maxGenomeVal = 1; /** The maximum value a gene can have */
static const uint maxSize = 50; /** The maximum number of Individual in this habitat */
static const double mutationRate = 0.05; /** The mutation rate for individuals during replication */
static const double migrationRate = 0.05; /** The migration rate for the Habitat */
static const double fitnessCutOff = 0.5; /** The fitness at which a background becomes a prey */
static const double minSizeFrac = 0.05; /** The minimum size of a Habitat in percent of maxSize. */
static const double killOffRate = 0.25; /** The percentage of Prey to kill off each generateion. */
static const double numGenerations = 500; /** The number of generations to run. */
